E_learning/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('quiz/', include('quiz.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .activate import activate

urlpatterns = [
  path('login/', views.LoginView.as_view(), name='login'),
	path('login/<next_url>/', views.LoginView.as_view(), name='login_next'),
	path('logout/', views.logout_view, name='logout'),
  path('signup/<str:user_role>/', views.SignUpView.as_view(), name='signup'),
  path('signup/<str:user_role>/<next_url>/', views.SignUpView.as_view(), name='signup_next'),
  path('activate/<uidb64>/<token>/', activate, name='activate_account'),
	path('student/profile/update/', views.GeneralProfileSettingsUpdateView.as_view(), name='student_profile_update'),
	path('instructor/profile/update/', views.ProfileUpdateView.as_view(), name='instructor_profile_update'),
  path('change/profile/image/', views.ProfileUpdationView.as_view(), name='change_profile_picture'),
	path('change-password/', views.PasswordChangeView.as_view(), name='change_password'),
]

# Django's built-in auth views patterns 
urlpatterns += [
  path('reset_password/', 
    auth_views.PasswordResetView.as_view(
      template_name='accounts/authentications/reset_password.html'), 
    name='reset_password'),

  path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(
      template_name='accounts/authentications/password_reset_sent.html'), 
    name='password_reset_done'),

  path('reset/<uidb64>/<token>', 
    auth_views.PasswordResetConfirmView.as_view(
      template_name='accounts/authentications/password_reset_form.html'),
    name='password_reset_confirm'),

  path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(
      template_name='accounts/authentications/password_reset_done.html'),
    name='password_reset_complete')
]

blog/urls.py
from django.urls import path
from . import views 

urlpatterns = [
	path('list/', views.PostListView.as_view(), name='posts_list'),
	path('<int:pk>/details/', views.PostDetailView.as_view(), name='post_details'),
	path('post/create/', views.ArticleCreateView.as_view(), name='create_post'),
	path('post/<slug:post_slug>/update/', views.ArticleUpdateView.as_view(), name='update_post'),
	path('post/<slug:post_slug>/<str:action>/', views.TrashUnTrashArticle.as_view(), name='trash_or_restore'),
	path('trash/list/', views.TrashListView.as_view(), name='open_trash'),
	path('trash/empty/', views.EmptyBlogTrashView.as_view(), name='empty_blog_trash'),
	path('<slug:post_slug>/add-comment/', views.PostCommentView.as_view(), name='add_comment'),
	path('comment/<int:comment_id>/reply/', views.CommentReplyView.as_view(), name='add_reply'),
	path('comment/<int:comment_id>/delete/', views.CommentDeleteView.as_view(), name='delete_comment'),
	path('comment/<int:comment_id>/reply/<int:reply_id>/delete/', views.CommentReplyDeleteView.as_view(), name='delete_reply'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from courses.models import Course
from courses.models import Subject

class User(AbstractUser):
  USER_CHOICES = (
    ('S', 'STUDENT'),
    ('I', 'INSTRUCTOR'),
  )
  GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
  )

  user_role     = models.CharField(max_length=15, choices=USER_CHOICES)
  gender        = models.CharField(max_length=10, choices=GENDER_CHOICES, default='M')
  profile_image = models.ImageField(upload_to='files/profile_images/', default='files/profile_images/default.png')

  def save(self, *args, **kwargs):
    created = self.id is None
    super(User, self).save(*args, **kwargs)
    if created and self.user_role == 'I':
      self.groups.add(Group.objects.get(pk=1))

  @property
  def full_name(self):
    return f"{self.first_name} {self.last_name}"

class InstructorProfile(models.Model):
  user   = models.OneToOneField(User, related_name='instructor_profile', on_delete=models.CASCADE)
  major_subjects    = models.ManyToManyField(Subject, blank=True)
  place_of_birth    = models.CharField(max_length=30, null=True, blank=True)
  about             = models.TextField(null=True, blank=True)
  achievements      = models.TextField(null=True, blank=True)
  objectives        = models.TextField(null=True, blank=True)
  facebook_profile  = models.URLField(null=True, blank=True)
  twitter_profile   = models.URLField(null=True, blank=True)
  github_profile    = models.URLField(null=True, blank=True)
  instagram_profile = models.URLField(null=True, blank=True)

  def enrolled_students(self):
    courses = self.courses.all()
    enrolled_students = []
    for course in courses:
      enrolled_students += course.students.all()
    return len(set(enrolled_students))

  def __str__(self):
    return f"{self.user.username} added as Instructor"


# <   1 - many
# >  many - many
# -  1 - 1

class StudentProfile(models.Model):
  user          = models.OneToOneField(User, 
                                      related_name='student_profile', 
                                      on_delete=models.CASCADE)
  bio           = models.TextField(null=True, blank=True)

  def get_unanswered_questions(self, quiz):
    answered_question = self.quiz_answers.filter(answer__question__quiz=quiz).values_list('answer__question__pk', flat=True)
    questions = quiz.questions.exclude(pk__in=answered_question)
    return questions

  def __str__(self):
    return f"{self.user.username} added as Student"

accounts/forms.py
from django import forms
from .models import StudentProfile, InstructorProfile, User

class SignUpForm(forms.Form):
	username  				= forms.CharField(max_length=20)
	gender  					= forms.ChoiceField(choices=(('M','Male'),('F', 'Female')))
	email  					  = forms.EmailField()
	password 					= forms.CharField(widget=forms.PasswordInput)
	confirm_password  = forms.CharField(widget=forms.PasswordInput)

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)
		for field_name in self.fields.keys():
			self.fields[field_name].widget.attrs.update({'class': 'form-control'})

	def clean_username(self):
		username = self.cleaned_data.get('username')
		alread_used_usernames = [user.username for user in User.objects.all()]
  
		if username in alread_used_usernames:
			raise forms.ValidationError("Username already in use.")
		return username

	def clean_confirm_password(self):
		passowrd1 = self.cleaned_data.get('password')
		password2 = self.cleaned_data.get('confirm_password')

		if passowrd1 != password2:
			raise forms.ValidationError('Mismatched Password')
		return password2

class StudentProfileSettingForm(forms.ModelForm):
	username   = forms.CharField(max_length=50)
	first_name = forms.CharField(max_length=20)
	last_name  = forms.CharField(max_length=20)
	email      = forms.EmailField()

	def __init__(self, user, *args, **kwargs):
		super(StudentProfileSettingForm, self).__init__(*args, **kwargs)
		self.fields['username'].initial = user.username
		self.fields['first_name'].initial = user.first_name
		self.fields['last_name'].initial = user.last_name
		self.fields['email'].initial = user.email

	class Meta:
		model = StudentProfile
		fields = ('username', 'first_name', 'last_name', 'email', 'bio')

class IntructorProfileSettingForm(forms.ModelForm):
	username   = forms.CharField(max_length=50)
	first_name = forms.CharField(max_length=20)
	last_name  = forms.CharField(max_length=20)
	email      = forms.EmailField()

	def __init__(self, user, *args, **kwargs):
		super(IntructorProfileSettingForm, self).__init__(*args, **kwargs)
		self.fields['username'].initial = user.username
		self.fields['first_name'].initial = user.first_name
		self.fields['last_name'].initial = user.last_name
		self.fields['email'].initial = user.email

	class Meta:
		model  = InstructorProfile
		fields = ('username', 'first_name', 'last_name', 'email', 'about')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.core.files import File
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.views.generic.edit import FormView
from django.views.generic.base import RedirectView, View, TemplateResponseMixin
from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
from django_email_verification import send_email

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from .forms import (
	SignUpForm, 
	StudentProfileSettingForm,
	IntructorProfileSettingForm,
)
from .tokens import account_activation_token
from django.template.loader import render_to_string
from .models import User, StudentProfile, InstructorProfile
from accounts.utils import save_courses_from_cookies_to_order
from courses.models import Course
import json

class LoginView(FormView):

	form_class    = AuthenticationForm
	template_name = 'accounts/authentications/login.html'
	next_url		  = None

	def dispatch(self, request, *args, **kwargs):
		if 'next_url' in kwargs:
			self.next_url = kwargs['next_url']
		return super(LoginView, self).dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		cd = form.cleaned_data
		user = authenticate(username=cd['username'], password=cd['password'])
		if user:
			login(self.request, user)
			if user.user_role == 'S':
				save_courses_from_cookies_to_order(self.request, user.student_profile)
		return super(LoginView, self).form_valid(form)

	def get_success_url(self):
		if self.next_url:
			return reverse_lazy(self.next_url)
		elif self.request.user.user_role == 'S':
			return reverse_lazy('home')
		elif self.request.user.user_role == 'I':
			return reverse_lazy('cms_home_page')
		return super(LoginView, self).get_success_url()

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['next_url'] = self.next_url
		return context

def logout_view(request):
	logout(request)
	response = redirect('login')
	response.delete_cookie('cart')
	return response

class SignUpView(TemplateResponseMixin, View):
	template_name = 'accounts/authentications/signup_form.html'
	model = None
	next_url = None

	def dispatch(self, request, user_role, *args, **kwargs):
		if user_role == 'S':
			self.model = StudentProfile
		elif user_role == 'I':
			self.model = InstructorProfile

		if 'next_url' in kwargs:
			self.next_url = kwargs['next_url']

		return super(SignUpView, self).dispatch(request, user_role, *args, **kwargs)

	def get(self, request, user_role, *args, **kwargs):
		form = SignUpForm()
		return self.render_to_response({'form':form, 'user_role': user_role})

	def post(self, request, user_role, *args, **kwargs):
		form = SignUpForm(request.POST)

		if form.is_valid():

			site = get_current_site(request)  # for domain

			cd = form.cleaned_data
			user = User(username=cd['username'], email=cd['email'], gender=cd['gender'])
			user.set_password(cd['confirm_password'])
			user.user_role = user_role
			user.is_active = False    # set as deactivated unless email confirmed...
			user.save()

			# create profile model associated with user
			user_profile = self.model(user=user)
			user_profile.save()

			message = render_to_string('accounts/emails/activate_account_mail.html', {
				'user': user,
				'protocol': 'http',
				'domain': site.domain,
				'uid': urlsafe_base64_encode(force_bytes(user.pk)),
				'token': account_activation_token.make_token(user)
			})

			message = Mail(
				from_email='adilsaleem1398@gmail.com',
				to_emails=[user.email],
				subject=f'Activate account for {site.domain}',
				html_content=message
			)

			try:
				sg_client = SendGridAPIClient('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')
				response = sg_client.send(message)
				messages.add_message(request, messages.SUCCESS, 'A verification email has been sent.')
				messages.add_message(request, messages.WARNING, 'Please also check your SPAM inbox!')
			except Exception as e:
				print(e)
				messages.add_message(request, messages.WARNING, str(e))

			if user:
				login(self.request, user)

			if user_role == 'S':
				save_courses_from_cookies_to_order(request, user_profile)

			if self.next_url:
				return redirect(self.next_url)
			return redirect('home')
		return self.render_to_response({'form': form})

# NO NEED TO USE THIS VIEW FOR NOW, I'LL REFACTOR THIS LATER...
class ProfileUpdateView(TemplateResponseMixin, View):
	template_name = 'accounts/authentications/profile_form.html'

	def get(self, request, *args, **kwargs):
		if request.user.user_role == 'S':
			form = StudentProfileSettingForm(request.user ,request.POST or None, request.FILES or None, instance=request.user.student_profile)

		elif request.user.user_role == 'I':
			form = IntructorProfileSettingForm(request.user ,request.POST or None, request.FILES or None, instance=request.user.instructor_profile)

		return self.render_to_response({'form': form})

	def post(self, request, *args, **kwargs):
		if request.user.user_role == 'S':
			form = StudentProfileSettingForm(request.user ,request.POST, request.FILES, instance=request.user.student_profile)

		elif request.user.user_role == 'I':
			form = IntructorProfileSettingForm(request.user ,request.POST, request.FILES, instance=request.user.instructor_profile)

		if form.is_valid():
			form.save()
			cd = form.cleaned_data
			request.user.username = cd['username']
			request.user.email = cd['email']
			request.user.first_name = cd['first_name']
			request.user.last_name = cd['last_name']
			request.user.save()

			if request.user.user_role =='S':
				return redirect('student_dashboard', request.user.student_profile.id)

			return redirect('home')
# ============================================================================================

class GeneralProfileSettingsUpdateView(CsrfExemptMixin, JsonRequestResponseMixin, View):
	def post(self, request, *args, **kwargs):
		if 'user_data' in request.POST:
			new_data = json.loads(request.POST['user_data'])
			request.user.email = new_data['email']
			request.user.first_name = new_data['firstname']
			request.user.last_name = new_data['lastname']
			request.user.save()

			response = {
				'username': request.user.username,
				'firstname': request.user.first_name,
				'lastname': request.user.last_name,
				'email': request.user.email
			}

			return self.render_json_response(response)
		return self.render_json_response({'message':'Something went wrong while updating'})

class ProfileUpdationView(CsrfExemptMixin, JsonRequestResponseMixin, View):
	def post(self, request, *args, **kwargs):
		if 'image_file' in request.FILES:
			filename = request.FILES['image_file'].name
			file_object = File(request.FILES['image_file'])			
			request.user.profile_image.save(filename, file_object)
		return self.render_json_response({})

class PasswordChangeView(TemplateResponseMixin, View):
  model = User
  template_name = 'accounts/authentications/password_change_form.html'

  def get(self, request, *args, **kwargs):
    form = PasswordChangeForm(request.user)
    return self.render_to_response({'form': form})

  def post(self, request, *args, **kwargs):
    form = PasswordChangeForm(request.user, request.POST)
    if form.is_valid():
      form.save()
      return redirect('login')

accounts/templates/accounts/authentications/instructor_signup.html
{% extends "base.html" %}

{% block title %}
	SignUp
 {% endblock %}

{% block content %}
	<h1>
		Sign Up as Instructor
	</h1>
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<p>
			<input type="submit" value="SignUp">
		</p>
	</form>
{% endblock %}

accounts/templates/accounts/authentications/login.html
{% extends "base.html" %}
{% load i18n %}
{% load socialaccount %}

{% load static %}

{% block title %} Login {% endblock %}

{% block content %}
  <style>
    html,body {
    height: 100%;
  }

  body.my-login-page {
    background-color: #f7f9fb;
    font-size: 14px;
  }

  .my-login-page .brand {
    width: 130px;
    height: 110px;
    overflow: hidden;
    margin: 40px auto;
    position: relative;
    z-index: 1;
  }

  .my-login-page .brand img {
    width: 100%;
  }

  .my-login-page .card-wrapper {
    width: 400px;
  }

  .my-login-page .card {
    margin-top: -70px;
    border-color: transparent;
    box-shadow: 0 4px 8px rgba(0,0,0,.05);
  }

  .my-login-page .card.fat {
    padding: 10px;
  }

  .my-login-page .card .card-title {
    margin-bottom: 30px;
  }

  .my-login-page .form-control {
    border-width: 2.3px;
  }

  .my-login-page .form-group label {
    width: 100%;
  }

  .my-login-page .btn.btn-block {
    padding: 12px 10px;
  }

  .my-login-page .footer {
    margin: 40px 0;
    color: #888;
    text-align: center;
  }

  @media screen and (max-width: 425px) {
    .my-login-page .card-wrapper {
      width: 90%;
      margin: 0 auto;
    }
  }

  #header-part, #footer-part{
    display: none;
  }

  @media screen and (max-width: 320px) {
    .my-login-page .card.fat {
      padding: 0;
    }

    .my-login-page .card.fat .card-body {
      padding: 15px;
    }
    
    #header-part, #footer-part{
      display: none;
    }
  }
  </style>
</head>

<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<img src="{% static 'files/utility_images/logo.png'%}" alt="logo">
					</div>
					<div class="card fat" style="box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;">
						<div class="card-body">
							<h4 class="card-title text-center">Login</h4>

              {% get_providers as socialaccount_providers %}
                {% if socialaccount_providers %}
                  <div class="socialaccount_ballot">
                    <ul class="socialaccount_providers text-center">
                      {% include "account/provider_list.html" with process="login" %}
                    </ul>
                  </div>
                <p class="text-center">-- OR --</p>
							<form method="POST" class="my-login-validation" novalidate="">
                {% csrf_token %}
								<div class="form-group">
									<label for="email">Username</label>
									{{ form.username }}
									<div class="invalid-feedback">
										Email is invalid
									</div>
								</div>
                <br>
								<div class="form-group">
                  <label for="password">Password</label>
                  {{ form.password }}
                  <div class="invalid-feedback">
                    Password is required
                  </div>
                  <a href="{% url 'reset_password' %}" class="float-right">
                    <small>Forgot Password?</small>
                  </a>
								</div>
                <br>
								<div class="form-group">
									<div class="custom-checkbox custom-control">
										<input type="checkbox" name="remember" id="remember" class="custom-control-input">
										<label for="remember" class="custom-control-label">Remember Me</label>
									</div>
								</div>
                <br>
								<div class="form-group m-0">
									<button type="submit" class="btn btn-primary btn-block">
										Login
									</button>
								</div>
                {% endif %}
								<div class="mt-4 text-center">
									Don't have an account? <a href="/accounts/signup/S/{% if next_url %}{{ next_url }}{% endif %}">SignUp</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2017 &mdash; Adna-Tech 
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

{% block javascript %}
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script>
    'use strict';

    $('#id_username').addClass('form-control');
    $('#id_password').addClass('form-control');

    $(function() {
      $("input[type='password'][data-eye]").each(function(i) {
        var $this = $(this),
          id = 'eye-password-' + i,
          el = $('#' + id);

        $this.wrap($("<div/>", {
          style: 'position:relative',
          id: id
        }));

        $this.css({
          paddingRight: 60
        });
        $this.after($("<div/>", {
          html: 'Show',
          class: 'btn btn-primary btn-sm',
          id: 'passeye-toggle-'+i,
        }).css({
            position: 'absolute',
            right: 10,
            top: ($this.outerHeight() / 2) - 12,
            padding: '2px 7px',
            fontSize: 12,
            cursor: 'pointer',
        }));

        $this.after($("<input/>", {
          type: 'hidden',
          id: 'passeye-' + i
        }));

        var invalid_feedback = $this.parent().parent().find('.invalid-feedback');

        if(invalid_feedback.length) {
          $this.after(invalid_feedback.clone());
        }

        $this.on("keyup paste", function() {
          $("#passeye-"+i).val($(this).val());
        });
        $("#passeye-toggle-"+i).on("click", function() {
          if($this.hasClass("show")) {
            $this.attr('type', 'password');
            $this.removeClass("show");
            $(this).removeClass("btn-outline-primary");
          }else{
            $this.attr('type', 'text');
            $this.val($("#passeye-"+i).val());				
            $this.addClass("show");
            $(this).addClass("btn-outline-primary");
          }
        });
      });

      $(".my-login-validation").submit(function() {
        var form = $(this);
            if (form[0].checkValidity() === false) {
              event.preventDefault();
              event.stopPropagation();
            }
        form.addClass('was-validated');
      });
    });
  </script>
{% endblock %}

accounts/templates/accounts/authentications/login_extra.html
{% load socialaccount %}

{% providers_media_js %}

accounts/templates/accounts/authentications/reset_password.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}

{% block content %}
  <div class="text-center mt-5" style="width: 80%; margin: 0 auto">
    <h1>Welcome to the Password Reset Page</h1>
    <p class="lead">
      Forgot your password? Please enter the email address you used to register
      with us and we will send you a link to reset your password
    </p>
  </div>
  <br/>

  <form action="" method="POST" class="text-center">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" id="submitbtn" value="Send"></p>
  </form>

  <div class="text-center">
    <a href="{% url 'login' %}">Back to login</a>
  </div>

{% endblock %}

{% block javascript %}
  <script>
    const email_field = document.querySelector('#id_email');
    email_field.className = 'form-control w-50 mx-auto';
    email_field.placeholder = 'abcd@example.com';

    const submit_btn = document.querySelector('#submitbtn');
    submit_btn.className = 'btn btn-primary';
  </script>
{% endblock %}

accounts/templates/accounts/authentications/signup_form.html
{% extends "base.html" %}
{% load static %}

{% block title %} SignUp {% endblock %}

{% block content %}

  <style>
    html,body {
    height: 100%;
  }

  body.my-login-page {
    background-color: #f7f9fb;
    font-size: 14px;
  }

  .my-login-page .brand {
    width: 130px;
    height: 110px;
    overflow: hidden;
    margin: 40px auto;
    position: relative;
    z-index: 1;
  }

  .my-login-page .brand img {
    width: 100%;
  }

  .my-login-page .card-wrapper {
    width: 400px;
  }

  .my-login-page .card {
    margin-top: -50px;
    border-color: transparent;
    box-shadow: 0 4px 8px rgba(0,0,0,.05);
  }

  .my-login-page .card.fat {
    padding: 10px;
  }

  .my-login-page .card .card-title {
    margin-bottom: 30px;
  }

  .my-login-page .form-control {
    border-width: 2.3px;
  }

  .my-login-page .form-group label {
    width: 100%;
  }

  .my-login-page .btn.btn-block {
    padding: 12px 10px;
  }

  .my-login-page .footer {
    margin: 40px 0;
    color: #888;
    text-align: center;
  }

  #header-part, #footer-part{
    display: none;
  }

  @media screen and (max-width: 425px) {
    .my-login-page .card-wrapper {
      width: 90%;
      margin: 0 auto;
    }
  }

  @media screen and (max-width: 320px) {
    .my-login-page .card.fat {
      padding: 0;
    }

    .my-login-page .card.fat .card-body {
      padding: 15px;
    }

    #header-part, #footer-part{
      display: none;
    }
  }
  </style>
</head>

<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<img src="{% static 'files/utility_images/logo.png'%}" alt="logo">
					</div>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title text-center">Create an Account</h4>
							<form method="POST" class="my-login-validation" novalidate="">
                {% csrf_token %}
								<div class="form-group">
									<label for="id_username">Username</label>
									{{ form.username }}
									<div class="invalid-feedback">
										Username not available
									</div>
								</div>

								<div class="form-group">
									<label for="id_email">E-Mail Address</label>
									{{ form.email }}
									<div class="invalid-feedback">
										Email is invalid
									</div>
								</div>

                <div class="form-group">
									<label for="id_password">Password
									</label>
									{{ form.gender }}
								    <div class="invalid-feedback">
								    	Gender is required
							    	</div>
								</div>

								<div class="form-group">
									<label for="id_password">Password
									</label>
									{{ form.password }}
								    <div class="invalid-feedback">
								    	Password is required
							    	</div>
								</div>

								<div class="form-group">
									<label for="id_confirm_password">Confirm
									</label>
									{{ form.confirm_password }}
								    <div class="invalid-feedback">
								    	Password didn't matched
							    	</div>
								</div>
                <br>
								<div class="form-group m-0">
									<button type="submit" class="btn btn-primary btn-block">
										SignUp
									</button>
								</div>
								<div class="mt-4 text-center">
									Already have an account? <a href="{% url 'login' %}">Login</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2017 &mdash; Adna-Tech 
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script>
    'use strict';

    $('#id_username').addClass('form-control');
    $('#id_password').addClass('form-control');
 
 </script>
{% endblock %}